# Generated by Django 5.1.3 on 2024-11-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.URLField(blank=True, help_text='Enter a valid URL for AI to generate questions.', null=True),
        ),
    ]
