# Generated by Django 5.1.3 on 2024-11-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_date',
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
