# Generated by Django 5.1.3 on 2024-11-26 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_creator_quiz_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_1', models.CharField(blank=True, max_length=200, null=True)),
                ('option_2', models.CharField(blank=True, max_length=200, null=True)),
                ('option_3', models.CharField(blank=True, max_length=200, null=True)),
                ('option_4', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
        ),
    ]
